'use strict';
// Ask-the-guide entries. Each answer agrees with the section named in `ref`;
// `k` adds search keywords a reader might use instead of the question's words.
const { FAIR, CP, PROGRAM, SYSTEMS, tierCount, shadowCount } = require('./model');

const F = (q, k, ref, a) => ({ q, k, ref, a });

const faq = [
  F('What is AI governance?', 'definition purpose decision rights', 'role', 'The decision rights, rules and evidence that let an organization use AI on purpose: it knows what AI it runs, who answers for each system, how risky each one is, and can prove each one does what was approved. It is not an ethics statement or a committee that reads every prompt.'),
  F('What is the difference between governance, compliance and responsible AI?', 'compliance ethics principles', 'role', '<b>Governance</b> is decision rights and accountability. <b>Compliance</b> is meeting specific external obligations. <b>Responsible AI</b> is the set of principles (fair, transparent, accountable, secure) that the rules put into practice.'),
  F('What are the three lines of defense?', 'first second third line audit', 'role', 'The first line (system owners) builds, runs and owns the risk. The second line (Governance Lead, Compliance, Model Risk) sets the rules and challenges the evidence. The third line (Internal Audit) tests whether the whole program works.'),
  F('Who sits on the AI Council and what can it decide?', 'council members chair vote quorum', 'doc-charter', 'The Chief Risk Officer chairs it, with Compliance (who can block on legal grounds), the CDO, CISO and a rotating business owner voting. It approves, conditions, pauses or prohibits Tier 1 systems, material changes and policy exceptions. Quorum is the chair plus three voting members including Compliance.'),
  F('Who can switch off an AI system?', 'kill switch pause stop', 'doc-charter', 'Any system owner, the Governance Lead or the CISO can pause a system immediately. The Council reviews every pause within 5 business days.'),
  F('What counts as an AI system?', 'definition scope vendor feature', 'inventory', 'Any system that produces predictions, classifications, recommendations, scores or generated content from data, including AI features switched on inside vendor products. Fixed hand-written rules are out.'),
  F('What goes on the intake form?', 'intake fields register', 'inventory', 'A named business owner, the purpose and the decision it influences, who is affected, the data used (including restricted classes), whether it is built, bought or a vendor feature, and who acts on the output.'),
  F('What is shadow AI and how do we find it?', 'unregistered unapproved discovery scan', 'inventory', `AI in use that was never registered. Meridian found ${shadowCount} through proxy-log and expense scans. Treat discovery as amnesty plus intake: register it within 30 days and it is not a policy violation.`),
  F('How many AI systems does Meridian have?', 'count inventory total', 'doc-inventory', `${SYSTEMS.length} found: ${tierCount(1)} Tier 1, ${tierCount(2)} Tier 2, ${tierCount(3)} Tier 3, ${tierCount(4)} Tier 4, and ${tierCount(0)} prohibited and blocked.`),
  F('How is the risk tier calculated?', 'score scoring formula risky riskiness impact autonomy exposure sensitivity', 'tiering', 'Score = 2 x impact + autonomy + exposure + data sensitivity, each 1 to 5. Tier 1 is 19 or more, Tier 2 14 to 18, Tier 3 9 to 13, Tier 4 8 or less. A consequential consumer decision with no human review is Tier 1 regardless of score.'),
  F('Why is impact counted twice?', 'weight double', 'tiering', 'Because a low-autonomy system can still be dangerous if its output steers a decision about someone\'s money, coverage or job. Doubling impact keeps that risk from being averaged away.'),
  F('What controls does each tier need?', 'tier controls count 24 17 10 5', 'doc-risk', 'Tier 1: all 24 controls, Council approval, independent validation, annual re-assessment. Tier 2: 17 controls and Governance Lead approval. Tier 3: 10 controls with owner attestation. Tier 4: 5 controls (register and follow the acceptable-use policy).'),
  F('Why is ClaimsPilot Tier 1?', 'claimspilot tier floor fast-track', 'doc-risk', `It scores 21 and also meets the floor rule: fast-track payments up to $${CP.stpCap.toLocaleString('en-US')} are made with no adjuster review, which is a consequential consumer decision.`),
  F('Which frameworks does the program map to?', 'NIST ISO 42001 NAIC EU AI Act regulation', 'frameworks', 'NIST AI RMF (GOVERN, MAP, MEASURE, MANAGE), ISO/IEC 42001 management-system clauses, and the NAIC Model Bulletin on the Use of AI Systems by Insurers. The EU AI Act is a reference only; it does not apply to Meridian\'s US business today.'),
  F('What does the NAIC AI bulletin expect from an insurer?', 'naic bulletin regulator insurer', 'frameworks', 'A written AI Systems program, governance and accountability, risk controls against adverse consumer outcomes, oversight of third-party AI, and documentation available to regulators. Compliance confirms current state adoption before controls change.'),
  F('What are the lifecycle gates?', 'gates G0 G1 G2 G3 G4 G5 stage', 'lifecycle', 'G0 intake and tiering, G1 design review, G2 validation, G3 go-live approval, G4 operate and monitor, G5 retire. Gates are fail-closed: missing evidence means not yet. A material change at G4 sends a system back to G0.'),
  F('Why must acceptance criteria be written before testing?', 'criteria validation before', 'lifecycle', 'Criteria written after results are seen will always be met. Validation at G2 checks results against dated criteria written at G1.'),
  F('How do you test for unfair discrimination without collecting race?', 'BIFSG inferred protected class proxy', 'fairness', 'Infer group membership in aggregate with BIFSG (surname and geography), use those labels only in a restricted test, compare each group\'s adverse-outcome rate with the reference group, and never attach inferred labels to an individual claim.'),
  F('What is the fairness threshold?', 'threshold ratio 1.25 four-fifths', 'fairness', `A group\'s adverse-outcome rate divided by the reference group\'s rate must not exceed ${FAIR.threshold}, the inverse of the four-fifths screen. A higher ratio is a finding that must be explained or fixed.`),
  F('What did the SentinelRisk fairness test find?', 'sentinelrisk fraud referral result', 'doc-impact', `Before the fix, ${FAIR.flaggedBefore.join(' and ')} claimants were referred to SIU at ratios above ${FAIR.threshold}. The cause was ${FAIR.removed} (a ZIP-code proxy) and ${FAIR.capped}. After removing one and capping the other, no group exceeds the threshold.`),
  F('What did the fairness fix cost?', 'trade-off precision fraud accuracy cost', 'doc-impact', `Referral precision fell from ${FAIR.precisionBefore}% to ${FAIR.precisionAfter}% and estimated fraud found from $${FAIR.fraudFoundBefore}M to $${FAIR.fraudFoundAfter}M a year. The Head of SIU and the CRO accepted that as the less discriminatory alternative.`),
  F('Why not just raise the cut-off for the flagged groups?', 'group-specific threshold option b', 'doc-impact', 'Because that uses group membership in a decision about an individual, which the policy prohibits. Inferred labels are allowed only for aggregate testing.'),
  F('What is the difference between human-in-the-loop and human-on-the-loop?', 'oversight loop pattern', 'oversight', 'In the loop: a person approves every output before it takes effect (SIU referrals). On the loop: outputs take effect but a person monitors and can reverse them (ClaimsPilot fast-track payments, sampled daily). Over the loop: a person sets rules and reviews periodically.'),
  F('How do I know human oversight is real?', 'override rate rubber stamp automation bias', 'oversight', `Track the override rate. Near zero usually means rubber-stamping; very high means the system is not useful. ClaimsPilot's band is ${CP.overrideBand[0]}% to ${CP.overrideBand[1]}%.`),
  F('What should a model card contain?', 'model card intended use limits', 'doc-model-card', 'Model details and owners, intended use, uses it must not be put to, training data, performance broken down by class, known limits and failure conditions, and human oversight: who can override and how fast.'),
  F('What must a vendor AI contract include?', 'contract clauses vendor audit change notice', 'vendors', 'Data-use limits (no training on our data without consent), notice before material model changes, incident notice within 72 hours, a test endpoint so we can run our own fairness tests, audit rights, and a deletion certificate on exit.'),
  F('Which vendor has the most gaps?', 'voxsight vendor findings', 'doc-vendor', 'VoxSight call analytics: it was bought without intake and lacks audit rights, test access, change notice and fairness results. Findings VD-01 and VD-02 are due by year end.'),
  F('What is model drift and how is it monitored?', 'drift PSI population stability', 'monitoring', `Drift is a shift in inputs or outcomes after approval. ClaimsPilot tracks input drift with PSI: amber at ${CP.psiAmber}, red at ${CP.psiRed}. August 2026 crossed amber during a hail event.`),
  F('What are the incident severity levels?', 'sev 1 sev 2 sev 3 severity', 'monitoring', 'Sev 1: harm at scale, legal breach or regulator inquiry; kill switch within 1 hour. Sev 2: red threshold or harm to identifiable people; fallback within 4 hours. Sev 3: amber threshold or a caught error with no harm.'),
  F('What happened in the hail-event incident?', 'AI-INC-2026-007 hail misroute', 'doc-monitoring', 'Severe misroutes reached 0.9% for 2 days, above the 0.5% red line. ClaimsPilot fell back to human triage for hail claims; 37 fast-tracked claims were re-reviewed and 3 claimants received supplemental payments totaling $4,180.'),
  F('Why keep a tamper-evident decision log?', 'audit trail log hash chain 7 years', 'monitoring', 'So a regulator or complaint question about one decision is a lookup, not a reconstruction. Tier 1 systems log inputs, model version, output and the human action in an append-only, hash-chained store kept 7 years.'),
  F('What is different about governing generative AI?', 'genai llm hallucination prompt injection leakage', 'genai', 'It can state falsehoods fluently, be steered by instructions hidden in documents (prompt injection), leak what it is given, and is used by everyone. Tiering and gates still apply; the tests add grounding with citations, red-team injection tests and DLP.'),
  F('Can I paste claim data into a chatbot?', 'acceptable use paste data chatgpt', 'doc-policy', 'Only into a tool approved for that data class. Claimant, health, payment or SSN data must never go into a consumer AI tool, browser extension or note-taker.'),
  F('What uses of AI are prohibited?', 'prohibited banned not allowed', 'doc-policy', 'Denying claims or cancelling policies with no human review; using protected characteristics (or inferred ones) in underwriting, pricing or claims decisions; emotion recognition or biometric categorization; uploading restricted data to unapproved tools; impersonation.'),
  F('How do policy exceptions work?', 'exception waiver expiry', 'doc-policy', 'Request through intake with the compensating control. Exceptions expire within 12 months. The Council approves for Tier 1 and 2; the Governance Lead for Tier 3 and 4. An expired exception is a finding.'),
  F('Which KPIs show the program is working?', 'kpi metrics measure program', 'kpis', `Inventory coverage, median intake-to-decision days (${PROGRAM.intakeDays[PROGRAM.intakeDays.length - 1]} against a target of ${PROGRAM.intakeTarget}), findings closed on time, override rates within band, and incidents by severity and how they were detected.`),
  F('What should I check before approving an AI-drafted governance document?', 'review approve checklist ai draft', 'review', 'Named owners, testable must-statements, dated evidence behind every claim, controls proportionate to tier, a described failure path, consistency with the inventory, and current regulatory references confirmed by Compliance.'),
  F('What is the most common failure in AI-drafted assessments?', 'invented evidence hallucinated results', 'review', 'Invented evidence: test results, dates and approvals that never happened, written confidently. Every number must trace to a test run or a source document; if it does not, record it as a finding.'),
];

module.exports = { faq };
