'use strict';
// Teaching sections: the discipline (10), judgment (3) and the worked example (1).
const P = require('../kit/parts');
const { ORG, TIER_RULES, SYSTEMS, tierName, tierCount, shadowCount, FAIR, CP, PROGRAM } = require('./model');
const { CONTROLS, controlsFor, GATES } = require('./controls');

const see = (key, n, title) => `<p>Applied in full in <a href="#doc-${key}">Document ${n}: ${title}</a>.</p>`;
const D = 'The discipline', J = 'Judgment';

const sections = [
  { id: 'role', group: D, title: '1. What AI governance is, and is not', html: `
<p><strong>AI governance</strong> is the set of decision rights, rules and evidence that lets an organization use AI on purpose: it knows what AI it runs, who answers for each system, how risky each one is, and can prove each one is doing what was approved. It is not an ethics statement, and it is not a committee that reads every prompt. Done well, it makes good projects <em>faster</em>, because teams know the path to yes.</p>
${P.table(['Term', 'What it means', 'Who owns it'], [
    ['Governance', 'Decision rights and accountability: who may approve what, on what evidence', 'AI Council, chaired by the Chief Risk Officer'],
    ['Risk management', 'Finding, sizing and treating the ways a system can cause harm', 'Governance Lead with system owners'],
    ['Compliance', 'Meeting specific external obligations (insurance regulators, privacy law)', 'Chief Compliance Officer'],
    ['Responsible AI', 'The principles (fair, transparent, accountable, secure) the rules put into practice', 'Everyone; written down in the policy'],
  ])}
<h3>Three lines of defense</h3>
${P.fig(P.flow({ title: 'Three lines of defense for AI at Meridian Mutual', width: 900, height: 200, nodes: [
    { id: 'a', x: 20, y: 30, w: 250, h: 70, t: 'First line: build and run', s: 'System owners, product, data science', kind: 'std' },
    { id: 'b', x: 325, y: 30, w: 250, h: 70, t: 'Second line: set and check', s: 'Governance Lead, Compliance, Model Risk', kind: 'gate' },
    { id: 'c', x: 630, y: 30, w: 250, h: 70, t: 'Third line: assure', s: 'Internal Audit', kind: 'out' },
    { id: 'd', x: 325, y: 130, w: 250, h: 50, t: 'AI Council (decides Tier 1)', kind: 'fact' },
  ], edges: [{ from: 'a', to: 'b', label: 'evidence' }, { from: 'b', to: 'c', label: 'control set' }, { from: 'b', to: 'd', label: 'recommends', side: 'v' }] }), 'The first line owns the risk. The second line writes the rules and challenges the evidence. The third line tests whether the whole system works.')}
${P.callout('warn', 'Red flag in AI output', 'A governance charter generated by AI that lists principles but names no decision owner, no tier, and no evidence. Ask: "Who can say no, and what would they need to see to say yes?" If the document cannot answer, it is not governance.')}
${see('charter', 1, 'AI Governance Charter &amp; Operating Model')}` },

  { id: 'inventory', group: D, title: '2. The AI inventory and use-case intake', html: `
<p>You cannot govern what you cannot see. The <strong>AI inventory</strong> is the register of every AI system in use or in build, with an owner, a purpose, a tier and a status. <strong>Intake</strong> is the front door: one short form, filed before anyone buys, builds or switches on AI. The inventory is the single most-requested artifact by regulators and auditors, so it must be complete before it is pretty.</p>
<h3>What counts as an AI system?</h3>
<p>Use a broad, testable definition: any system that produces predictions, classifications, recommendations, scores or generated content from data, including vendor products with AI features switched on. Spreadsheets with fixed formulas are out; a vendor CRM whose "smart" lead score is on is in.</p>
${P.table(['Intake field', 'Why it matters'], [
    ['Business owner (a named person)', 'Accountability; a team name cannot be held to account'],
    ['Purpose and the decision it influences', 'Drives the impact score; "efficiency" is not a purpose'],
    ['Who is affected (consumers, employees, neither)', 'Drives exposure and notice duties'],
    ['Data used, including restricted classes', 'Drives sensitivity and the data approval'],
    ['Build, buy or vendor feature', 'Decides whether vendor controls apply'],
    ['Autonomy: who acts on the output', 'A score that pays a claim is not the same as a score a person reads'],
  ])}
${P.callout('info', 'Shadow AI is normal; ignoring it is not', `Meridian's first proxy-log and expense scan found ${shadowCount} AI systems nobody had registered (a call-analytics tool and a browser note-taker). Treat discovery as amnesty plus intake, not punishment, or the next one will be hidden better.`)}
${see('inventory', 3, 'AI System Inventory')}` },

  { id: 'tiering', group: D, title: '3. Risk tiering: proportionate control', html: `
<p>Not every AI system deserves the same scrutiny. <strong>Risk tiering</strong> sorts systems so that a fraud score that triggers investigations gets independent validation and fairness testing, while a coding assistant gets a registration and a policy acknowledgement. Without tiers, governance either strangles low-risk work or waves through high-risk work.</p>
<h3>The TrustLine scoring rule</h3>
${P.pre('Score = 2 x Impact + Autonomy + Exposure + Data sensitivity      (each 1 to 5, max 25)\nTier 1 >= 19   Tier 2 14-18   Tier 3 9-13   Tier 4 <= 8\nFloor: a consequential decision about a consumer with no human review is Tier 1.\nProhibited uses (see policy) are not tiered; they are stopped.')}
${P.table(['Tier', 'Score', 'Controls required', 'Systems at Meridian'], TIER_RULES.map((r, i) => [r.name, i === 0 ? '19 to 25' : `${r.min} to ${TIER_RULES[i - 1].min - 1}`, r.controls, String(tierCount(r.tier))]))}
${P.table(['Factor', '1 (low)', '5 (high)'], [
    ['Impact (counted twice)', 'Inconvenience; easily reversed', 'Money, coverage, employment or legal rights; hard to reverse'],
    ['Autonomy', 'A person reads it and decides', 'The system acts with no review'],
    ['Exposure', 'A few internal users', 'Every customer or every claim'],
    ['Data sensitivity', 'Public or synthetic data', 'Health, financial or biometric data'],
  ])}
${P.chartRow(P.barChart({ title: 'Tiering scores by system (max 25)', data: SYSTEMS.filter((s) => s.tier > 0).sort((a, b) => b.score - a.score).map((s) => ({ label: s.short, value: s.score, tone: s.tier === 1 ? 'cherry' : s.tier === 2 ? 'berry' : 'muted' })), max: 25 }))}
${P.callout('tip', "Reviewer's shortcut", 'Impact is counted twice on purpose. A system can be low-autonomy and still dangerous if its output steers a decision about someone\'s money. When an AI draft scores impact low, ask what happens to the person if the output is wrong.')}
${see('risk', 4, 'AI Risk Assessment &amp; Tiering')}` },

  { id: 'frameworks', group: D, title: '4. Frameworks and regulation', html: `
<p>You do not need to memorize regulations. You need to know which frameworks your controls answer to, and to keep one <strong>crosswalk</strong> that shows each control's mapping, so a new rule becomes a gap analysis, not a new program.</p>
${P.table(['Source', 'What it is', 'What it asks of you'], [
    ['NIST AI Risk Management Framework 1.0', 'US voluntary framework: four functions, GOVERN, MAP, MEASURE, MANAGE', 'A culture and structure for risk (Govern), context and risks known (Map), risks measured (Measure), risks treated and monitored (Manage)'],
    ['ISO/IEC 42001', 'Certifiable AI management system standard (management-system clauses 4 to 10)', 'Policy, roles, risk assessment, operational controls, performance evaluation, continual improvement'],
    ['NAIC Model Bulletin on the Use of AI Systems by Insurers', 'US insurance regulators\' expectations, adopted by many states', 'A written AI Systems program, governance and accountability, risk controls against adverse consumer outcomes, oversight of third-party AI, and documentation available to regulators'],
    ['State unfair-discrimination and privacy laws', 'Existing insurance and consumer law applied to AI', 'Rates and claim practices must not unfairly discriminate, whatever tool produced them'],
    ['EU AI Act', 'Risk-based EU regulation (prohibited, high-risk, transparency tiers)', 'Not applicable to Meridian\'s six US states today; a useful reference for tier design'],
  ])}
${P.callout('warn', 'Check the current text', 'This summary is for orientation, not legal advice. Regulations and their adoption change; Compliance confirms the current obligations for each state before a control is retired or relaxed.')}
<p>The crosswalk lives in the control framework: each of the ${CONTROLS.length} TrustLine controls names its NIST function, ISO/IEC 42001 clause area and NAIC bulletin theme.</p>
${see('controls', 7, 'Control Framework &amp; Regulatory Crosswalk')}` },

  { id: 'lifecycle', group: D, title: '5. Controls and gates across the lifecycle', html: `
<p>Controls attach to <strong>gates</strong>: points in a system's life where evidence is checked before it moves on. Gates are fail-closed: missing evidence means "not yet", never "assume fine". Tier decides which controls a gate checks, not whether the gate exists.</p>
${P.fig(P.flow({ title: 'TrustLine lifecycle gates', width: 1000, height: 150, nodes: GATES.map((g, i) => ({ id: g[0], x: 10 + i * 165, y: 40, w: 145, h: 66, t: g[0], s: g[1], kind: g[0] === 'G3' ? 'gate' : g[0] === 'G4' ? 'out' : 'std' })),
    edges: GATES.slice(1).map((g, i) => ({ from: GATES[i][0], to: g[0] })) }), 'Material change at G4 sends a system back to G0. Retirement (G5) keeps the records.')}
${P.table(['Gate', 'Question it answers', 'Evidence checked', 'Controls at this gate'], GATES.map((g) => [`${g[0]} ${g[1]}`, g[2], g[3], String(CONTROLS.filter((c) => c.gate === g[0]).length)]))}
${P.callout('tip', 'Write acceptance criteria before testing', 'Validation (G2) checks results against criteria written at design (G1). Criteria written after the results are seen will always be met. Ask for the dated criteria document.')}
${see('controls', 7, 'Control Framework &amp; Regulatory Crosswalk')}` },

  { id: 'fairness', group: D, title: '6. Fairness and unfair-discrimination testing', html: `
<p>An AI system can discriminate without ever seeing a protected attribute, because other inputs act as <strong>proxies</strong>: ZIP code, address history and credit-based scores can all correlate with race. Fairness testing measures outcomes by group and asks whether any gap is justified by the business purpose and could not be closed by a less discriminatory alternative.</p>
<h3>How Meridian tests</h3>
${P.list([
    'Infer group membership in aggregate with BIFSG (surname and geography), because insurers do not collect race. Inferred labels are used only for testing and never attached to a claim.',
    'Compute each group\'s adverse-outcome rate (for SentinelRisk, the SIU referral rate) and divide it by the reference group\'s rate.',
    `A ratio above <strong>${FAIR.threshold}</strong> (the inverse of the four-fifths screen) is a finding that must be explained or fixed.`,
    'Find the driving features, test a less discriminatory alternative, and record the accuracy cost of the fix.',
  ], true)}
${P.chartRow(P.barChart({ title: 'SIU referral-rate ratio vs reference, before fix', data: FAIR.groups.filter((g) => g.g !== FAIR.reference).map((g) => ({ label: g.g, value: g.ratioBefore, tone: g.ratioBefore > FAIR.threshold ? 'cherry' : 'berry' })), max: 1.8 }),
    P.barChart({ title: 'Ratio after removing the ZIP proxy', data: FAIR.groups.filter((g) => g.g !== FAIR.reference).map((g) => ({ label: g.g, value: g.ratioAfter, tone: g.ratioAfter > FAIR.threshold ? 'cherry' : 'leaf' })), max: 1.8 }))}
${P.callout('warn', 'Red flag in AI output', 'A fairness section that reports overall accuracy only, or says the model is fair "because it does not use race". Both miss proxies entirely. Ask for outcome rates by group, the threshold, and the features driving any gap.')}
${see('impact', 5, 'Algorithmic Impact Assessment: SentinelRisk')}` },

  { id: 'oversight', group: D, title: '7. Transparency, explainability and human oversight', html: `
<p><strong>Transparency</strong> tells people AI is involved. <strong>Explainability</strong> gives the person acting on an output a reason they can check. <strong>Human oversight</strong> makes sure a person can catch and reverse a wrong output in time. All three fail when they exist only on paper.</p>
${P.table(['Oversight pattern', 'What the person does', 'Use it when', 'Meridian example'], [
    ['Human-in-the-loop', 'Approves every output before it takes effect', 'High impact, low volume', 'SIU investigator decides on every SentinelRisk referral'],
    ['Human-on-the-loop', 'Monitors outputs and can stop or reverse them', 'High volume, reversible, capped', `ClaimsPilot fast-track payments up to $${CP.stpCap.toLocaleString('en-US')}, sampled daily`],
    ['Human-over-the-loop', 'Sets rules and reviews performance periodically', 'Low impact', 'DeskAssist usage reviewed quarterly'],
  ])}
<h3>Is the oversight real?</h3>
<p>Track the <strong>override rate</strong>: how often people change the AI's output. Near zero usually means rubber-stamping (automation bias); very high means the system is not useful. ClaimsPilot's target band is ${CP.overrideBand[0]}% to ${CP.overrideBand[1]}%.</p>
${P.chartRow(P.lineChart({ title: 'ClaimsPilot adjuster override rate (%)', labels: CP.months, values: CP.override, unit: '%', min: 0, max: 14 }))}
${P.callout('tip', 'Ask for the reason, not the weights', 'A useful explanation is one the reader can act on: "referred because the loss was reported 2 days after policy start and the repair shop is on the watch list", not a chart of feature importance.')}
${see('model-card', 6, 'Model Card: ClaimsPilot AI')}` },

  { id: 'vendors', group: D, title: '8. Third-party and vendor AI', html: `
<p>Most enterprise AI is bought, not built. Buying a model does not transfer accountability: regulators hold the insurer responsible for a vendor model's outcomes. Vendor governance is due diligence before signature, contract terms that give you evidence, and monitoring after go-live.</p>
${P.table(['Ask the vendor for', 'Why', 'Walk away if'], [
    ['Model documentation: purpose, training data sources, known limits', 'You must explain the system to regulators', 'Everything is "proprietary"'],
    ['Fairness testing results, and the right to run your own tests', 'You carry the unfair-discrimination risk', 'They refuse test access to scored outputs'],
    ['Notice before material model changes', 'A silent retrain is a new, unapproved system', 'Changes ship without notice'],
    ['Data-use limits: no training on your data without consent', 'Your claimants\' data must not leave its purpose', 'Terms allow training on customer data by default'],
    ['Audit rights and incident notice (72 hours)', 'You need evidence when something goes wrong', 'No audit clause'],
  ])}
${P.callout('warn', 'Red flag in AI output', 'A vendor assessment that copies the vendor\'s own marketing claims ("bias-free", "explainable AI") as evidence. Evidence is a test result you can rerun, a contract clause, or a document with a date.')}
${see('vendor', 8, 'Third-Party AI Due Diligence')}` },

  { id: 'monitoring', group: D, title: '9. Monitoring, incidents and the audit trail', html: `
<p>Approval is a snapshot; production is a movie. Models <strong>drift</strong> when the world changes (a hail season, a new repair-shop network), vendors retrain, and prompts get edited. Monitoring watches inputs, outputs and outcomes against thresholds; incident response decides what happens when a threshold is crossed; the <strong>audit trail</strong> proves what the system did and who acted.</p>
${P.chartRow(P.lineChart({ title: 'ClaimsPilot input drift (PSI)', labels: CP.months, values: CP.psi, target: CP.psiAmber, min: 0, max: 0.14 }))}
<p>The dashed line is the amber threshold (PSI ${CP.psiAmber}). August crossed it during a hail event; the red-line rule on severe misroutes triggered automatic fallback to human triage within the hour.</p>
${P.table(['Severity', 'Definition', 'Response'], [
    ['Sev 1', 'Consumer harm at scale, a legal breach, or a regulator inquiry', 'Kill switch now; Council chair and Compliance within 1 hour'],
    ['Sev 2', 'Red threshold crossed or harm to identifiable people', 'Fallback within 4 hours; root cause in 5 business days'],
    ['Sev 3', 'Amber threshold or a caught error with no harm', 'Fix in the normal backlog; review at the monthly forum'],
  ])}
${P.callout('info', 'Tamper-evident decision logs', 'Tier 1 systems log every AI-influenced decision (inputs, model version, output, the human action) in an append-only, hash-chained store kept for 7 years. A regulator question about one claim becomes a lookup, not a reconstruction.')}
${see('monitoring', 9, 'Monitoring &amp; AI Incident Response Plan')}` },

  { id: 'genai', group: D, title: '10. Generative AI: what changes', html: `
<p>Generative AI adds risks that predictive models do not have: it can state falsehoods fluently, be steered by instructions hidden in a document (<strong>prompt injection</strong>), leak what it was given, and is used by every employee, not just a model team. The tiering and gates still apply; the tests change.</p>
${P.table(['Risk', 'Control', 'Evidence'], [
    ['Fabricated answers', 'Ground answers in approved sources and require citations; refuse when no source', 'Golden-set accuracy and citation checks'],
    ['Prompt injection from documents or email', 'Treat retrieved text as data; tool permissions limited to the task', 'Red-team test log'],
    ['Data leakage', 'Enterprise tenant with no training on prompts; DLP on restricted data', 'Contract clause and DLP rule'],
    ['Unvetted employee use', 'Approved tools list; acceptable-use rules; blocked consumer tools', 'Proxy logs, policy acknowledgements'],
  ])}
${P.callout('tip', 'Acceptable use in one line', 'Employees may use approved AI tools for drafting and summarizing; they may not paste claimant, health or payment data into any tool not approved for it, and they own anything they send.')}
${see('policy', 2, 'Responsible AI Policy')}` },

  { id: 'good-bad', group: J, title: 'Good vs bad governance', eyebrow: 'Judgment', html: `
${P.table(['Area', 'Bad (reject)', 'Good (approve)'], [
    ['Inventory', 'A spreadsheet updated once a year by asking around', 'Intake required before purchase or build; proxy and expense scans find the rest'],
    ['Tiering', 'Every system gets the same 40-question review', 'A scored rule puts effort where impact is; low tiers clear in days'],
    ['Policy', 'Principles with no "must" statements', 'Testable rules, prohibited uses, an exception process with expiry'],
    ['Fairness', '"We do not use race, so we are fair"', 'Outcome rates by group, a threshold, proxy analysis, recorded trade-off'],
    ['Oversight', 'A human "in the loop" who approves 99.9% in 4 seconds', 'Override rate tracked within a band; reviewers have time and authority'],
    ['Vendors', 'Marketing claims accepted as evidence', 'Test access, change notice and audit rights in the contract'],
    ['Monitoring', 'Accuracy checked at launch only', 'Thresholds with named responders and automatic fallback'],
    ['Council', 'Meets to receive updates', 'Meets to decide, with a decision record and dissent noted'],
  ])}` },

  { id: 'kpis', group: J, title: 'KPIs for an AI governance program', eyebrow: 'Judgment', html: `
<p>Measure whether governance is <em>working</em> (risk is controlled) and whether it is <em>usable</em> (teams are not routing around it). A program that only reports activity, such as meetings held or policies written, cannot show either.</p>
${P.tiles([
    { v: `${SYSTEMS.length - SYSTEMS.filter((s) => s.tier === 0).length} / ${SYSTEMS.length}`, l: 'AI systems registered and tiered', s: '1 prohibited and blocked' },
    { v: '100%', l: 'Tier 1 in production with current assessment', s: '2 of 2; RateSense not yet live', tone: 'good' },
    { v: `${PROGRAM.intakeDays[PROGRAM.intakeDays.length - 1]} days`, l: 'Median intake-to-decision', s: `target ${PROGRAM.intakeTarget}; was ${PROGRAM.intakeDays[0]}`, tone: 'good' },
    { v: `${PROGRAM.findings.high}`, l: 'Open high findings', s: `${PROGRAM.findings.medium} medium, ${PROGRAM.findings.low} low`, tone: 'warn' },
    { v: `${PROGRAM.trainingPct}%`, l: 'Policy acknowledgement', s: `of ${ORG.employees.toLocaleString('en-US')} employees` },
    { v: `${PROGRAM.incidents}`, l: 'AI incidents (2026)', s: '0 Sev 1' },
  ])}
${P.chartRow(P.lineChart({ title: 'Median days from intake to decision', labels: PROGRAM.quarters, values: PROGRAM.intakeDays, target: PROGRAM.intakeTarget, min: 0, max: 45 }))}
${P.table(['KPI', 'Why it matters', 'Watch for'], [
    ['Inventory coverage', 'Ungoverned AI is the largest risk', 'Shadow AI found by scans rather than intake'],
    ['Intake-to-decision time', 'Slow governance gets bypassed', 'Rising time with a flat volume'],
    ['Findings closed on time', 'Findings that never close are decoration', 'Repeated extensions on the same finding'],
    ['Override rate within band', 'Shows oversight is real', 'Rates near zero'],
    ['Incidents by severity and detection source', 'Monitoring should find problems before customers do', 'Incidents found by complaints'],
  ])}` },

  { id: 'review', group: J, title: 'The review lens: approving AI-generated governance work', eyebrow: 'Judgment', html: `
<p>AI will draft your policies, assessments and model cards in minutes. Your job is to <strong>direct</strong> it with a precise brief, <strong>evaluate</strong> the draft against a known standard, and <strong>approve</strong> only what an examiner, an auditor and a harmed customer would all accept.</p>
${P.table(['Check', 'Question to ask', 'Reject if'], [
    ['Ownership', 'Is every control, finding and decision owned by a named person?', 'Owners are teams or "TBD"'],
    ['Testability', 'Could an auditor test each "must" and get a yes or no?', 'Statements use "appropriate", "where possible", "periodically"'],
    ['Evidence', 'Does each claim point to an artifact with a date?', 'Claims rest on assertions or vendor marketing'],
    ['Proportionality', 'Do controls scale with tier?', 'Low-risk tools carry the full Tier 1 burden, or the reverse'],
    ['Failure path', 'What happens when a threshold is crossed or a control fails?', 'Only the approval path is described'],
    ['Consistency', 'Do tiers, counts and names match the inventory?', 'The same system has different tiers in two documents'],
    ['Currency', 'Are regulatory references current and confirmed by Compliance?', 'Citations are vague or undated'],
  ])}
<h3>A brief that gets a usable first draft</h3>
${P.pre(`Draft a [document] for [system] at [organization].
Context: [purpose, decision it influences, who is affected, data classes, vendor or in-house].
Tier: [n], scored [impact/autonomy/exposure/sensitivity]. Applicable controls: [ids].
Standards: NIST AI RMF function per control; NAIC AI bulletin themes; our policy [section].
Must include: named owners, dated evidence for every claim, thresholds with red-line actions,
the failure path, open issues. Do not invent test results; mark missing evidence as a finding.`)}
${P.callout('warn', 'The most common AI drafting failure', 'Invented evidence: test results, dates and approvals that never happened, written in a confident register. Every number in an assessment must trace to a test run or a source document. If it does not, it is a finding, not a fact.')}` },

  { id: 'example', group: 'The worked example', title: 'The example: Meridian Mutual Insurance TrustLine', eyebrow: 'The worked example', html: `
<p class="lede">${ORG.name} writes personal auto and homeowners insurance in ${ORG.states} states. Over three years it adopted AI in claims (ClaimsPilot, Lumina), fraud (SentinelRisk), service (PolicyLens, PulseNotify, VoxSight), finance (the LedgerOne reserve forecast) and everyday work (DeskAssist, CodeAssist), each approved separately or not at all. Its domestic regulator adopted the NAIC AI bulletin, and Internal Audit could not produce a complete list of AI in use. <strong>TrustLine</strong> is the program that fixes that: one inventory, one tiering rule, one control set, one council.</p>
${P.tiles([
    { v: String(SYSTEMS.length), l: 'AI systems found', s: `${shadowCount} by shadow-AI scan` },
    { v: String(tierCount(1)), l: 'Tier 1 systems', s: 'ClaimsPilot, SentinelRisk, RateSense', tone: 'warn' },
    { v: String(CONTROLS.length), l: 'Controls in the framework', s: 'mapped to NIST, ISO, NAIC' },
    { v: FAIR.total.toLocaleString('en-US'), l: 'Claims in the fairness test', s: FAIR.window },
    { v: `${FAIR.flaggedBefore.length} to ${FAIR.flaggedAfter.length}`, l: 'Groups over the 1.25 ratio', s: 'before and after the fix', tone: 'good' },
    { v: `${CP.firstContactBefore}h to ${CP.firstContactAfter}h`, l: 'FNOL to first contact', s: 'ClaimsPilot, governed' },
  ])}
${P.chartRow(P.donut({ title: 'AI systems by tier', data: [1, 2, 3, 4, 0].map((t) => ({ label: tierName(t), value: tierCount(t), tone: t === 1 || t === 0 ? 'cherry' : t === 2 ? 'berry' : 'muted' })).filter((d) => d.value), center: String(SYSTEMS.length) }))}
${P.table(['Objective', 'Measure', 'Target'], [
    ['Know all AI in use', 'Systems registered and tiered / systems found', '100%, every quarter'],
    ['Govern in proportion', 'Median intake-to-decision days', `${PROGRAM.intakeTarget} days or less`],
    ['No unfair discrimination', 'Groups above the 1.25 outcome-ratio threshold on Tier 1 consumer systems', '0, tested quarterly'],
    ['Oversight that works', 'Override rate inside its band on every Tier 1 system', '100% of months'],
    ['Examination-ready', 'Days to produce the AI program package for a regulator', '2 business days'],
  ])}
${P.callout('info', 'All figures are illustrative', `Volumes, rates, names and test results in this guide are invented for teaching and kept consistent across every document. ${ORG.name} is the fictional carrier used throughout this accelerator's field guides.`)}` },
];

module.exports = { sections };
